---
language: node_js

matrix:
  include:
    - os: osx
      node_js: "4"
      osx_image: xcode7.3
      env: ELECTRON_PLATFORM=darwin
    - os: linux
      node_js: "4"
      sudo: required
      dist: trusty
      env: ELECTRON_PLATFORM=linux CC=clang CXX=clang++ npm_config_clang=1

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - clang
      - xvfb

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - '[ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || export PATH="$PATH:node_modules/ember-cli/bin"'
  - ember electron:package --platform $ELECTRON_PLATFORM --arch x64
  - ls -lah electron-builds
