---
language: node_js
node_js:
  - "4"

osx_image: xcode7.3
sudo: required
dist: trusty

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
    - node_modules
    - node_modules/electron-prebuilt

addons:
  apt:
    packages:
      - clang
      - xvfb

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - ls -lah
  - npm config list
  - ls -lah $HOME/.npm/lib/node_modules/ /usr/local/share/npm/ /usr/local/share/npm/bin node_modules
  - echo $PATH
  - export PATH="node_modules/ember-cli/bin:$PATH"
  - echo $PATH
  - node --version
  - ember electron:package --platform $TRAVIS_OS_NAME --arch x64
  - ls -lah electron-builds
