---
language: node_js
node_js:
  - "4"

osx_image: xcode7.3
sudo: required
dist: trusty

matrix:
  include:
    - os: osx
      env: ELECTRON_PLATFORM=darwin
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 ELECTRON_PLATFORM=linux

cache:
  directories:
    - node_modules
    - node_modules/electron-prebuilt

addons:
  apt:
    packages:
      - clang
      - xvfb

before_install:
  - npm config set spin false
  - npm install -g bower

install:
  - npm install
  - bower install

script:
  - '[ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || export PATH="$PATH:node_modules/ember-cli/bin"'
  - echo $PATH
  - ember electron:package --platform $ELECTRON_PLATFORM --arch x64
  - ls -lah electron-builds
