version: 0.0.{build}

platform:
  - x64

cache:
  - node_modules
  - bower_components
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\Roaming\bower'

install:
  - ps: Install-Product node 6 x64
  - npm install bower -g
  - npm install
  - bower install

build_script:
  - node --version
  - cd
  - SET PATH=%cd%\node_modules\ember-cli\bin;%PATH%
  - DIR %cd%\node_modules\ember-cli\bin
  - SET
  - node node_modules\ember-cli\bin\ember electron:package --platform win32 --arch x64
  - ember electron:package --platform win32 --arch x64
  - ps: ls electron-builds

test: off
