# This will only run on tagged commits
# as it's purpose is for packaging for
# Windows at release. This is set in the
# appveyor account
version: 0.0.{build}

platform:
  - x64

cache:
  - node_modules
  - bower_components
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 6 x64
  - npm install bower -g
  - npm install
  - bower install

build_script:
  - node --version
  - node node_modules\ember-cli\bin\ember electron:package --platform win32 --arch x64
  - 7z a electron-builds\exercism-gui-win32-x64-%APPVEYOR_REPO_TAG_NAME%.zip electron-builds\exercism-gui-win32-x64
  - ps: ls electron-builds

test: off

deploy:
  release: exercism-gui-win32-x64-$APPVEYOR_REPO_TAG_NAME
  provider: GitHub
  auth_token:
    secure: 4Lc+r0RBFpZLKT+JZ5tlHQsEttScYJBtrTQ9BmtYQqcZyXlMP8v/+wjrBRdtY4XO
  artifact: electron-builds\.*.zip
  on:
    appveyor_repo_tag: true
